about/urls.py
from django.urls import path, include
from .views import index,form,savekegi


app_name = "about"
urlpatterns = [
    path('about/', index, name='index'),
    path('form/', form, name='form'),
    path('form/savekegi',savekegi),
]

tk1_covid/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('', include('about.urls')),
    path('authentication/', include('authentication.urls')),
    path('article/', include('article.urls'))

]

about/models.py
from django.db import models

# Create your models here.

CHOICES= [
    ('Full Stack Developer', 'Full Stack Developer'),
    ('Front-End Developer', 'Front-End Developer'),
    ('Back-End Developer', 'Back-End Developer'),
    ]
class User(models.Model):
    name= models.CharField(max_length=100)
    role= models.CharField(max_length=100, choices= CHOICES)

about/forms.py
from django import forms  
from .models import User


CHOICES= [
    ('Full Stack Developer', 'Full Stack Developer'),
    ('Front-End Developer', 'Front-End Developer'),
    ('Back-End Developer', 'Back-End Developer'),
    ]

class UserForm(forms.ModelForm):
    name= forms.CharField(max_length=100)
    role= forms.CharField(widget=forms.Select(choices=CHOICES))
    class Meta:
        model = User
        fields =['name','role']

about/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponseRedirect
from django.views.generic import FormView  
from .models import User 
from .forms import UserForm


def index(request):
    objs = User.objects.all()
    return render(request, 'about/indexx.html',{'objs':objs})
def form(request):
    response={ 'form':UserForm}
    return render(request, 'about/form.html',response)


def savekegi(request):
    form = UserForm(request.POST or None)
    f = form.save()
    if(form.is_valid and request.method == 'POST'):
        f.save()
        return HttpResponseRedirect('/about')
    else:
        return HttpResponseRedirect('/form')

about/templates/about/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'about/style.css' %}">
    <title>CegahCovid</title>
</head>

<body>

    <!-- navbar -->
    {% include 'navbar.html' with current="about" %}

    {% block content %}
    
    
    {% endblock %}
    <!-- Footer -->
    <footer class="page-footer font-small cyan darken-3">
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3 text-light bg-dark">© 2020 Copyright:
            <a href="https://mdbootstrap.com/"> CegahCovid</a>
        </div>
    </footer>


    <!-- script -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>

about/templates/about/form.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    Form Member
{% endblock %}


{% block body %}
  {% include 'navbar.html' with current="form" %}
    
            
                <form action="savekegi" method="POST">
                    {% csrf_token %}
                    
                    <table  cellspacing="15" style="margin-left: auto; margin-right: auto; margin-top: 40px;" >
                        {{form.as_table}}
                    </table>
                    <input type="submit" class="btn btn-success" value="Submit" style="margin-bottom: 353px; margin-left: 660px; margin-top: 50px;"> 
            
                    
                    
                </form>
                
        
{% endblock %}

about/templates/about/indexx.html
{% extends 'template.html' %}
{% load static %}

{% block title %}
    About Us
{% endblock %}


{% block body %}
  {% include 'navbar.html' with current="about" %}
        <img src="{% static 'about/DR.png' %}" class="img-fluid" alt="Responsive image">
      <h1 style="font-size:4vw;text-align: center;position: relative;top: 70px;">About Us</h1>
      
      <p class="text-justify" style="margin-top: 100px;">CegahCovid adalah situs yang berisikan tentang artikel-artikel kesehatan,
        utamanya dalam rangka mencegah penyebarluasan pandemi COVID-19.
        Website ini menawarkan pengalaman baru dalam melakukan pencegahan,
        yaitu menulis artikel. User dapat menulis artikel yang nantinya akan dipublish.
        Dengan demikian, harapannya masyarakat akan lebih aware dalam menghadapi pandemi ini.</p>
      <h2 style="text-align: center;margin-top: 80px;">Team</h2>
        
      <div class="row" style="margin-top: 100px; margin-left: 100px; margin-right: 100px;">
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/ibnu.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <h5 class="card-title">Ibnu Hambali</h5>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/irza.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <h5 class="card-title">Muhammad Irza</h5>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/mario.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <h5 class="card-title">Mario Serano</h5>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
        <div class="col-sm-3">
          <div class="card text-center">
            <img src="{% static 'about/aryo.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
            <div class="card-body">
              <h5 class="card-title">Maximilian Aryo</h5>
              <p class="card-text">Full Stack Developer</p>
            </div>
          </div>
        </div>
      </div> 
    <h2 style="text-align: center; margin-top: 100px;">Click button below to join us!</h2>
    
    <a class="btn btn-info" href="{% url 'about:form' %}" role="button"  style="margin-left: 50%;margin-right: auto; margin-top: 30px; margin-bottom: 30px;">join</a>
    {% if objs.count > 0 %}
    <h2 style="text-align: center;margin-top: 80px;">Additional Team Member</h2>
    
    <div class="row" style="margin-top: 100px; margin-left: 100px; margin-right: 100px;">
      {% for item in objs %}
      <div class="col-sm-3">
        <div class="card text-center" style="margin-bottom: 30px;">
          <img src="{% static 'about/fb1.png' %}" class="card-img-top" alt="..." style="width: 3cm; height: 4cm; margin-left: auto; margin-right: auto; display: block;">
          <div class="card-body">
            <h5 class="card-title">{{item.name}}</h5>
            <p class="card-text">{{item.role}}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>

    


    {% endif %}

    {% endblock %}